name: NotKillRank
version: '${project.version}'
main: me.ihqqq.notkillrank.NotKillRank
api-version: '1.21'
load: POSTWORLD
authors: [ihqqq]
description: Elo rankings, Kill Streaks, Bounty, Anti-Farm for NotMC

softdepend: [PlaceholderAPI]

commands:
  elo:
    description: Xem elo của bạn hoặc người khác
    usage: /elo [player]
  top:
    description: Bảng xếp hạng top 10 elo
    usage: /top
  stats:
    description: Xem thông kê cá nhân
    usage: /stats [player]
  bounty:
    description: Đặt truy nã lên người chơi
    usage: /bounty <player> <elo>
  notkillrank:
    description: Lệnh quản trị NotKillRank
    usage: /notkillrank <reload|reset <player>|setelo <player> <elo>>
    aliases: [nkr]

permissions:
  notkillrank.use:
    description: Cho phép dùng lệnh cơ bản
    default: true
  notkillrank.admin:
    description: Cho phép dùng lệnh admin
    default: op
