name: NotKillRank
version: '${project.version}'
main: me.ihqqq.notkillrank.NotKillRank
api-version: '1.21'
load: POSTWORLD
authors: [ihqqq]
description: Elo rankings, Kill Streaks, Bounty, Anti-Farm for NotMC

softdepend: [PlaceholderAPI, SkinsRestorer, PvPManager]

commands:
  elo:
    description: Xem elo của bạn hoặc người khác
    usage: /elo [player]
  top:
    description: Bảng xếp hạng top 10 elo
    usage: /top
  stats:
    description: Xem thông kê cá nhân
    usage: /stats [player]
  bounty:
    description: Đặt truy nã lên người chơi
    usage: /bounty <player> <elo>
  notkillrank:
    description: Lệnh quản trị NotKillRank
    usage: /notkillrank <reload|reset <player>|setelo <player> <elo>>
    aliases: [nkr]

permissions:
  notkillrank.use:
    description: Cho phép dùng lệnh cơ bản
    default: true
  notkillrank.admin:
    description: Cho phép dùng lệnh admin
    default: op
  notkillrank.antifarm.max.5:
    description: Giới hạn anti-farm 5 kill/giờ trên cùng 1 người
    default: false
  notkillrank.antifarm.max.10:
    description: Giới hạn anti-farm 10 kill/giờ trên cùng 1 người
    default: false
  notkillrank.antifarm.max.15:
    description: Giới hạn anti-farm 15 kill/giờ trên cùng 1 người
    default: false
  notkillrank.antifarm.max.20:
    description: Giới hạn anti-farm 20 kill/giờ trên cùng 1 người
    default: false
  notkillrank.antifarm.bypass:
    description: Bypass hoàn toàn giới hạn anti-farm
    default: false
